
public enum ItemType
{
    CHEESECAKESTRAW, CUPCAKEREDVELVET,
    LEMONADE,ORANGEJUÝCE,CUPCAKECHERRY,BURGER,BREAD ,


    CHEESECAKESTRAWAREA, CUPCAKEREDVELVETAREA,
    LEMONADEAREA, ORANGEJUÝCEAREA, CUPCAKECHERRYAREA, BURGERAREA, BREADAREA, NONE
      
}

public interface IGetItem 
{

    public ItemType GetItem();


}

