
public enum ItemType
{
    POTATO, CHEESECAKESTRAW, CUPCAKEREDVELVET, DOUGHNUT, DOUGHNUTPINK,
    ESPRESSOCUP, LEMONADE,TEACUP,ORANGEJUÝCE,CUPCAKECHERRY,BURGER,BREAD , PIZZA, NONE
      
}

public interface IGetItem 
{

    public ItemType GetItem();


}
